spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/forum-db
    username: docker
    password: docker
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret: aec6dad242f0e7c11ebd2d1ba5d9d6b0